# Generated by Django 4.1 on 2022-09-02 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mascotas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gato',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='perro',
            name='fecha_nacimiento',
        ),
        migrations.AddField(
            model_name='gato',
            name='raza',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perro',
            name='raza',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
