# Generated by Django 4.1 on 2022-09-02 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mascotas', '0002_remove_gato_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('animal_tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Conejo',
        ),
    ]
